api:
  client-id: app-ifto
  secret-id: 0b666933-4eeb-4bd8-a760-aa69a76241f6

server:
  port: 8081
token:
  secret:
    store-pass: ${TOKEN_SECRET_STORE_PASS}
    pair-alias: ${TOKEN_SECRET_PAIR_ALIAS}
  validity:
    seconds: 2550
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/application_ifto
    username: ${user}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
  flyway:
    locations: classpath:db/migration
